config/routes.rb
# config/routes.rb

Rails.application.routes.draw do
  get "up" => "rails/health#show", view: :rails_health_check

  resources :lists, only: [:index, :show, :new, :create, :destroy] do
    resources :bookmarks, only: [:new, :create, :destroy]
  end

  resources :movies, only: [:index]

  root "lists#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/bookmark.rb
class Bookmark < ApplicationRecord
  belongs_to :movie
  belongs_to :list

  validates :comment, length: { minimum: 6 }
  validates :movie_id, uniqueness: { scope: :list_id }

  # ...
end

app/models/list.rb
class List < ApplicationRecord
  has_many :bookmarks, dependent: :destroy
  has_many :movies, through: :bookmarks

  validates :name, presence: true, uniqueness: true

  after_destroy :destroy_associated_movies

  private

  def destroy_associated_movies
    movies.destroy_all
  end
end

app/models/movie.rb
class Movie < ApplicationRecord
  has_many :bookmarks

  validates :title, presence: true, uniqueness: true
  validates :overview, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/bookmarks_controller.rb
# app/controllers/bookmarks_controller.rb
class BookmarksController < ApplicationController
  before_action :set_list, only: [:new, :create]
  before_action :set_bookmark, only: [:destroy]

  def new
    @movies = Movie.all
    @bookmark = @list.bookmarks.build
  end

  def create
    @movies = Movie.all
    @bookmark = @list.bookmarks.build(bookmark_params)
    if @bookmark.save
      redirect_to list_path(@list), notice: 'Bookmark was successfully created.'
    else
      render :new
    end
  end

  def destroy
    @bookmark.destroy
    respond_to do |format|
      format.html { redirect_to list_path(@bookmark.list), notice: 'Bookmark was successfully destroyed.' }
    end
  end

  private

  def set_list
    @list = List.find(params[:list_id])
  end

  def set_bookmark
    @bookmark = Bookmark.find(params[:id])
  end

  def bookmark_params
    params.require(:bookmark).permit(:comment, :movie_id)
  end
end

app/controllers/concerns/movies_controller.rb
class MoviesController < ApplicationController
  def index
    @movies = Movie.all
    @list = List.find_by(name: 'Your List Name') # Adjust this based on your requirements
  end
end

app/controllers/lists_controller.rb
class ListsController < ApplicationController
  def index
    @lists = List.all
  end

  def show
    @list = List.find(params[:id])
  end

  def new
    @list = List.new
  end

  def destroy
    @list = List.find(params[:id])
    @list.destroy
    redirect_to lists_path, notice: 'List was successfully destroyed.'
  end

  def create
    @list = List.new(list_params)
    if @list.save
      redirect_to list_path(@list), notice: 'List was successfully created.'
    else
      render :new
    end
  end

  private

  def list_params
    params.require(:list).permit(:name)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bookmarks_helper.rb
module BookmarksHelper
end

app/helpers/lists_helper.rb
module ListsHelper
end

app/views/bookmarks/_form.html.erb
<% @bookmark ||= @list.bookmarks.build %>

<%= simple_form_for [@list, @bookmark] do |f| %>
  <%= f.collection_select :movie_id, Movie.all, :id, :title, label: 'Select a Movie' %>
  <%= f.input :comment %>
  <%= f.button :submit %>
<% end %>

app/views/bookmarks/destroy.js.erb
// app/views/bookmarks/destroy.js.erb
// Cette vue sera appelée après la suppression via AJAX

// Vous pouvez ajouter ici du code JavaScript pour mettre à jour la page, par exemple en supprimant le bookmark de la liste
$('#<%= dom_id(@bookmark) %>').remove();

app/views/bookmarks/new.html.erb
<h1>New Bookmark</h1>
<%= render 'form' %>
<%= link_to 'Back', list_path(@list) %>

app/views/bookmarks/show.html.erb
<!-- app/views/bookmarks/show.html.erb -->
<h1><%= @bookmark.comment %></h1>
<p>Movie: <%= @bookmark.movie.title %></p>
<p>List: <%= @bookmark.list.name %></p>

<%= link_to 'Back', list_path(@bookmark.list) %>
<%= link_to 'Remove Bookmark', list_bookmark_path(@bookmark.list, @bookmark), method: :delete, data: { confirm: 'Are you sure?' } %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsWatchList</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/lists/_form.html.erb
<%= simple_form_for @list do |f| %>
  <%= f.input :name %>
  <%= f.button :submit %>
<% end %>

app/views/lists/index.html.erb
<!-- app/views/lists/index.html.erb -->

<h1>All Lists</h1>

<ul>
  <% @lists.each do |list| %>
    <li>
      <%= link_to list.name, list_path(list) %>
      <%= form_for(list, url: list_path(list), method: :delete, data: { confirm: 'Are you sure?' }) do |f| %>
        <%= f.submit 'Delete', class: 'delete-list-button' %>
      <% end %>
    </li>
  <% end %>
</ul>

<%= link_to 'New List', new_list_path %>

app/views/lists/new.html.erb
<h1>New List</h1>

<%= render 'form' %>

<%= link_to 'Back', lists_path %>

app/views/lists/show.html.erb
<!-- app/views/lists/show.html.erb -->
<h1><%= @list.name %></h1>

<%= render 'bookmarks/form', list: @list %>

<h2>Bookmarks</h2>
<ul>
  <% @list.bookmarks.each do |bookmark| %>
    <li>
      <% if bookmark.movie.present? %>
        <%= "#{bookmark.movie.title}: #{bookmark.comment}" %>
        <%= link_to 'Remove Bookmark', list_bookmark_path(@list, bookmark), method: :delete, class: 'remove-bookmark-link' %>
    </li>
      <% end %>
  <% end %>

<%= link_to 'View All Movies', movies_path %>
<%= link_to 'Back', lists_path %>

app/views/movies/index.html.erb
<!-- app/views/movies/index.html.erb -->

<h1>All Movies</h1>

<ul>
  <% @movies.each do |movie| %>
    <li>
      <%= movie.title %> - <%= movie.overview %>
    </li>
  <% end %>
</ul>

<%= link_to 'Back', :back %>